version: "3.9"

services:
  app:
    build: .
    container_name: nib_procurement_app
    ports:
      - "9003:9002"
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://nibprocure:nibprocure@db:5432/nibprocure?schema=public"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16-alpine
    container_name: nib_procurement_db
    environment:
      POSTGRES_USER: nibprocure
      POSTGRES_PASSWORD: nibprocure
      POSTGRES_DB: nibprocure
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
